### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by WallasAR** [WallasAR/UmbrellaMarketplace#1]
## Tasks (06-11-2024):
- [x] Create new branch backend name;
- [x] Create FAQS Page;
- [x] Create login screens and authentication system;
- [ ] Responsivity in pages (home and product);
- [ ] Integrate the API that calculates shipping prices - useful links: [Free API Integration with Better Shipping (bye bye Correios)](https://www.youtube.com/watch?v=haHn2sMGnzY);
- [ ] Fix carousel on Home Page - change images too;
- [ ] Fix problem when change info in profile;
- [ ] Make search bar functional;
- [ ] Add cards skeletons and error msgs for final users(in case not server running);
- [ ] See possibility of Deploy website for free Cloudflare Pages;
- [ ] Update Angular to fix problems with css in deploy https://github.com/tailwindlabs/tailwindcss/issues/16147;
